package Enums;

public enum Effects {
    //NONE
    NONE(0),
    //ONEEFFECT
    AFTERBURNER(1),
    ASTEROIDFIELD(2),
    GASCLOUD(4),
    SUPERFOOD(8),
    SHIELD(16),
    //TWOEFFECT
    SHIELD_SUPERFOOD(24),
    SHIELD_GASCLOUD(20),
    SHIELD_ASTEROIDFIELD(18),
    SHIELD_AFTERBURNER(17),
    SUPERFOOD_GASCLOUD(12),
    SUPERFOOD_ASTEROIDFIELD(10),
    SUPERFOOD_AFTERBURNER(9),
    GASCLOUD_ASTEROIDFIELD(6),
    GASCLOUD_AFTERBURNER(5),
    ASTEROIDFIELD_AFTERBURNER(3),
    //THREEEFFECT
    SHIELD_SUPERFOOD_GASCLOUD(28),
    SHIELD_SUPERFOOD_ASTEROIDFIELD(26),
    SHIELD_SUPERFOOD_AFTERBURNER(25),
    SHIELD_GASCLOUD_ASTEROIDFIELD(22),
    SHIELD_GASCLOUD_AFTERBURNER(21),
    SHIELD_ASTEROIDFIELD_AFTERBURNER(19),
    SUPERFOOD_GASCLOUD_ASTEROIDFIELD(14),
    SUPERFOOD_GASCLOUD_AFTERBURNER(13),
    SUPERFOOD_ASTEROIDFIELD_AFTERBURNER(11),
    GASCLOUD_ASTEROIDFIELD_AFTERBURNER(7),
    //FOUREFFECT
    SHIELD_SUPERFOOD_GASCLOUD_ASTEROIDFIELD(30),
    SHIELD_SUPERFOOD_GASCLOUD_AFTERBURNER(29),
    SHIELD_SUPERFOOD_ASTEROIDFIELD_AFTERBURNER(27),
    SHIELD_GASCLOUD_ASTEROIDFIELD_AFTERBURNER(23),
    SUPERFOOD_GASCLOUD_ASTEROIDFIELD_AFTERBURNER(15),
    //FIVEEFFECT
    SHIELD_SUPERFOOD_GASCLOUD_ASTEROIDFIELD_AFTERBURNER(31);

    public final Integer value;

    Effects(Integer value){
        this.value = value;
    }
    
    public static Effects val(Integer valuee) {
        for (Effects eff : Effects.values()) {
          if (eff.value == valuee) return eff;
        }

        throw new IllegalArgumentException("Value not found");
    }

    public Integer getHashCode(){
        return this.value;
    }
}
